# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature-ms-patricioGuerra-mensaje
pool: 'Default'
 #vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    


  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud_final'
      organization: 'devops-trabajo-final'
      scannerMode: 'Other'
  

  - task: Gradle@3
    inputs:
     gradleWrapperFile: 'gradlew'
     tasks: 'sonarqube'
     publishJUnitResults: true
     testResultsFiles: '**/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     sonarQubeRunAnalysis: true
     sqGradlePluginVersionChoice: 'specify'
     sonarQubeGradlePluginVersion: '3.3'
     spotBugsAnalysis: false
    displayName: SonarCloud Analysis


  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

  - task: Docker@2
    displayName: iniciar docker
    inputs:
      containerRegistry: 'docker-devops'
      command: 'login'

  - task: Docker@2
    displayName: construir imagen
    inputs:
      containerRegistry: 'docker-devops'
      repository: 'patowagen/microservicio-spring'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: latest

  - task: Docker@2
    displayName: Lanzar imagen 
    inputs:
      containerRegistry: 'docker-devops'
      repository: 'patowagen/microservicio-spring'
      command: 'push'
      tags: 'latest'

  - task: KubectlInstaller@0
    inputs:
      kubectlVersion: 'latest'
    displayName: Instalacion Kubectl


  - task: Kubernetes@1
    displayName: Kubernetes container deploy
    inputs:
      connectionType: 'None'
      namespace: 'default'
      command: 'apply'
      arguments: '-f deployment-app.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'